export const API = {
  TOKEN: 'https://id.twitch.tv/oauth2/token',
  AUTHORIZE: 'https://id.twitch.tv/oauth2/authorize',
  USERS: 'https://api.twitch.tv/helix/users',
  CHANNELS: 'https://api.twitch.tv/helix/channels',
  ANALYTICS: 'https://api.twitch.tv/helix/analytics',
  BITS: 'https://api.twitch.tv/helix/bits',
  CHANNEL_POINTS: 'https://api.twitch.tv/helix/channel_points',
  CHARITY: 'https://api.twitch.tv/helix/charity',
  CHAT: 'https://api.twitch.tv/helix/chat',
  CLIPS: 'https://api.twitch.tv/helix/clips',
  CONDUITS: 'https://api.twitch.tv/helix/eventsub/conduits',
  CCL: 'https://api.twitch.tv/helix/content_classification_labels',
  ENTITLEMENTS: 'https://api.twitch.tv/helix/entitlements',
  EXTENSIONS: 'https://api.twitch.tv/helix/extensions',
  EVENTSUB: 'https://api.twitch.tv/helix/eventsub',
  GAMES: 'https://api.twitch.tv/helix/games',
  GOALS: 'https://api.twitch.tv/helix/goals',
  GUEST_STAR: 'https://api.twitch.tv/helix/guest_star',
  HYPETRAIN: 'https://api.twitch.tv/helix/hypetrain',
  MODERATION: 'https://api.twitch.tv/helix/moderation',
  POLLS: 'https://api.twitch.tv/helix/polls',
  STREAMS: 'https://api.twitch.tv/helix/streams',
};
