const HELIX = 'https://api.twitch.tv/helix';

export const API = {
  TOKEN: 'https://id.twitch.tv/oauth2/token',
  AUTHORIZE: 'https://id.twitch.tv/oauth2/authorize',
  USERS: `${HELIX}/users`,
  CHANNELS: `${HELIX}/channels`,
  ANALYTICS: `${HELIX}/analytics`,
  BITS: `${HELIX}/bits`,
  CHANNEL_POINTS: `${HELIX}/channel_points`,
  CHARITY: `${HELIX}/charity`,
  CHAT: `${HELIX}/chat`,
  CLIPS: `${HELIX}/clips`,
  CCL: `${HELIX}/content_classification_labels`,
  ENTITLEMENTS: `${HELIX}/entitlements`,
  EXTENSIONS: `${HELIX}/extensions`,
  EVENTSUB: `${HELIX}/eventsub`,
  GAMES: `${HELIX}/games`,
  GOALS: `${HELIX}/goals`,
  GUEST_STAR: `${HELIX}/guest_star`,
  HYPETRAIN: `${HELIX}/hypetrain`,
  MODERATION: `${HELIX}/moderation`,
  POLLS: `${HELIX}/polls`,
  STREAMS: `${HELIX}/streams`,
};
